### ISSUE TITLE
Where to find the Objective function in the code

### ISSUE THREAD

**Issue by madoka109** [Vanint/TADE-AgnosticLT#10]
In 4.3 of the paper, objective function is used to calculate the weight of each expert, I guess it is in test_all.py, but I can't find it.
Please tell me the spefic position in the code, thank you!

**Comment by YifanZhang07** [comment]
Hi test_all.py is a file to test models. Please refer to test_training files.

**Comment by madoka109** [comment]
I find it, thanks!
