### ISSUE TITLE
About CIFAR10-LT's Implementation details

### ISSUE THREAD

**Issue by sunhappy6900** [Vanint/TADE-AgnosticLT#11]
Hello，
In your paper,the top-1 accuracy on CIFAR10-LT(Imbalance Ratio=10,100) is 90.8% and 83.8%,but when I run your source code,the top-1 accuracy on CIFAR10-LT(Imbalance Ratio=10,100) is 90.16% and 82.92%,What are the specific Implementation details on CIFAR10-LT?
Thank you~

**Comment by YifanZhang07** [comment]
Hi, if I remember correctly: On CIFAR10-LT, you need to change "reduce_dimension" to False, and adjust the learning rate to 0.05. You can have a try first for this configuration. Thanks.

**Comment by sunhappy6900** [comment]
Is the learning rate always fixed at 0.05 in 200 epochs?

**Comment by YifanZhang07** [comment]
No, I use the same learning rate decay strategy as CIFAR100-LT.

![image](https://user-images.githubusercontent.com/26360112/158996945-2c58b1ee-aecb-43c9-be70-d62ad90e05ca.png)

**Comment by sunhappy6900** [comment]
thank you,let me have a try.

**Comment by sunhappy6900** [comment]
thank you，this worked.

**Comment by Huangszz** [comment]
> thank you，this worked.

Could you please provide the config file for CIFAR10? @sunhappy6900
