### ISSUE TITLE
About Backbone

### ISSUE THREAD

**Issue by oldfemalepig** [Vanint/TADE-AgnosticLT#3]
Hi,
Thank you very much for your work. I would like to ask if you tried to use ResNeXt101-32x4d instead of ResNeXt50 in your experiments. After my experiments, ResNeXt101 is not as effective as ResNeXt50. 
Are there any other parameters that need to be changed besides the backbone?

Best,

**Comment by YifanZhang07** [comment]
Hi, thanks for your attention. Yes, I have tried ResNeXt101 on ImageNet-LT, which performs higher than ResNeXt50. What is your performance on this backbone？

**Comment by oldfemalepig** [comment]
> Hi, thanks for your attention. Yes, I have tried ResNeXt101 on ImageNet-LT, which performs higher than ResNeXt50. What is your performance on this backbone？

It reached 57.18 based on ResNetXt101 with epochs:200、batchsize: 128、lr：0.025. 
Should I tweak the epochs and lr further？
Can I ask you how your parameters are set?

**Comment by YifanZhang07** [comment]
> > Hi, thanks for your attention. Yes, I have tried ResNeXt101 on ImageNet-LT, which performs higher than ResNeXt50. What is your performance on this backbone？
> 
> It reached 57.18 based on ResNetXt101 with epochs:200、batchsize: 128、lr：0.025. Should I tweak the epochs and lr further？ Can I ask you how your parameters are set?

You can try batch size 64, epoch 180, lr 0.025. If I remember correctly, such a setting achieves about 59.2.
