### ISSUE TITLE
variable s in ResNet_s

### ISSUE THREAD

**Issue by sunhappy6900** [Vanint/TADE-AgnosticLT#6]
Hi,
Why did you add a variable s(s=30) in ResNet_s

**Comment by YifanZhang07** [comment]
Hi, the main function of "s" is to adjust the logit magnitude of the cosine classifier if you use such a classifier. In contrast, if you use a linear classifier, "s" would be adjusted to 1 according to the code.

Moreover, this architecture is following RIDE (please refer to https://github.com/frank-xwang/RIDE-LongTailRecognition/blob/main/model/ldam_drw_resnets/ride_resnet_cifar.py). For simplicity, we do not change this hyper-parameter.

**Comment by sunhappy6900** [comment]
thank you~
